name: R4B-Deploy Cloud Functions

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        type: choice
        options:
          - Dev
          - QA
          - Prod
      dry_run:
        description: "Run as Dry Run "
        required: true
        type: boolean
      git_tag:
        description: "Git tag or commit to checkout"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      # Validate Git Tag
      - name: Validate Git Tag based on Environment
        run: |
          ENVIRONMENT="${{ github.event.inputs.environment }}"
            TAG="${{ github.event.inputs.git_tag }}"
            EXPECTED_PREFIX="CloudFunctions-${ENVIRONMENT}-v"

          if echo "$TAG" | grep -Eq "^${EXPECTED_PREFIX}[0-9]+$"; then
            echo "‚úîÔ∏è The provided deployment tag - '$TAG' aligns with the selected $ENVIRONMENT environment."
          else
            echo "‚ùå ERROR: The tag '$TAG' does not match the expected naming convention for the '$ENVIRONMENT' environment."
             exit 1
          fi
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_tag }}

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraform Init
      - name: Terraform Init
        working-directory: CloudFunctions/terraform
        run: |
          ENVIRONMENT=$(echo "${{ github.event.inputs.environment }}" | tr '[:upper:]' '[:lower:]')
          echo "‚öôÔ∏è Initializing Terraform backend for environment: $ENVIRONMENT"

          terraform init -reconfigure \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="prefix=cloud-functions-${ENVIRONMENT}-state"

      # Terraform Plan
      - name: Terraform Plan
        working-directory: CloudFunctions/terraform
        run: |
          FUNCTIONS_LIST=$(echo "${{ vars.FUNCTIONS_LIST }}" | sed 's/\([^,]*\)/"&"/g')

          # Common var block (reusable for plan and apply)
          TF_VARS="
            -var=project_id=${{ vars.PROJECT_ID }} \
            -var=region=${{ vars.REGION }} \
            -var=functions=[$FUNCTIONS_LIST] \
            -var=registry_pwd=${{ secrets.NPM_PASSWORD }} \
            -var=source_bucket=${{ vars.SOURCE_BUCKET }} \
            -var=secret_project_id=${{ vars.GOOGLE_SECRET_PROJECT_ID }} \
            -var=token_url=${{ vars.TOKEN_URL }} \
            -var=scope=${{ vars.SCOPE }} \
            -var=token_refresh_time=${{ vars.TOKEN_REFRESH_TIME }} \
            -var=client_id_secret=${{ vars.CLIENT_ID_KEY }} \
            -var=client_secret_secret=${{ vars.CLIENT_SECRET_KEY }} \
            -var=config_bucket_name=${{ vars.CONFIG_BUCKET_NAME }} \
            -var=config_file_path=${{ vars.CONFIG_FILE_PATH }} \
          "

          echo "üßæ Running Terraform Plan for environment: ${{ github.event.inputs.environment }}"

          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            echo "üß™ Dry Run mode enabled ‚Äî no state update, no apply."
            terraform plan -lock=false -input=false $TF_VARS
          else
            echo "‚òÅÔ∏è Apply mode ‚Äî generating deployment plan."
            terraform plan -out=tfplan.out -lock=true -input=false $TF_VARS
          fi

      # Terraform Apply
      - name: Terraform Apply
        if: ${{ github.event.inputs.dry_run == 'false' }}
        working-directory: CloudFunctions/terraform
        run: |
          echo "üöÄ Applying Terraform plan for Cloud Functions..."
          terraform apply -auto-approve tfplan.out
